# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mcorr_viz_template_dockwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VizualizationWidget(object):
    def setupUi(self, VizualizationWidget):
        VizualizationWidget.setObjectName("VizualizationWidget")
        VizualizationWidget.resize(299, 162)
        self.label = QtWidgets.QLabel(VizualizationWidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 17))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(VizualizationWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 281, 96))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonViewDownsampleMCMovie = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonViewDownsampleMCMovie.setObjectName("pushButtonViewDownsampleMCMovie")
        self.gridLayout.addWidget(self.pushButtonViewDownsampleMCMovie, 2, 0, 1, 2)
        self.pushButtonInputMovie = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonInputMovie.setObjectName("pushButtonInputMovie")
        self.gridLayout.addWidget(self.pushButtonInputMovie, 1, 0, 1, 1)
        self.pushButtonViewProjection = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonViewProjection.setObjectName("pushButtonViewProjection")
        self.gridLayout.addWidget(self.pushButtonViewProjection, 0, 1, 1, 2)
        self.pushButtonCnImage = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonCnImage.setObjectName("pushButtonCnImage")
        self.gridLayout.addWidget(self.pushButtonCnImage, 1, 1, 1, 2)
        self.spinBoxDownsampleWindow = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxDownsampleWindow.setMaximum(200)
        self.spinBoxDownsampleWindow.setSingleStep(1)
        self.spinBoxDownsampleWindow.setProperty("value", 4)
        self.spinBoxDownsampleWindow.setDisplayIntegerBase(10)
        self.spinBoxDownsampleWindow.setObjectName("spinBoxDownsampleWindow")
        self.gridLayout.addWidget(self.spinBoxDownsampleWindow, 2, 2, 1, 1)
        self.comboBoxProjection = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxProjection.setObjectName("comboBoxProjection")
        self.comboBoxProjection.addItem("")
        self.comboBoxProjection.addItem("")
        self.comboBoxProjection.addItem("")
        self.gridLayout.addWidget(self.comboBoxProjection, 0, 0, 1, 1)

        self.retranslateUi(VizualizationWidget)
        QtCore.QMetaObject.connectSlotsByName(VizualizationWidget)
        VizualizationWidget.setTabOrder(self.comboBoxProjection, self.pushButtonViewProjection)
        VizualizationWidget.setTabOrder(self.pushButtonViewProjection, self.pushButtonInputMovie)
        VizualizationWidget.setTabOrder(self.pushButtonInputMovie, self.pushButtonCnImage)
        VizualizationWidget.setTabOrder(self.pushButtonCnImage, self.pushButtonViewDownsampleMCMovie)
        VizualizationWidget.setTabOrder(self.pushButtonViewDownsampleMCMovie, self.spinBoxDownsampleWindow)

    def retranslateUi(self, VizualizationWidget):
        _translate = QtCore.QCoreApplication.translate
        VizualizationWidget.setWindowTitle(_translate("VizualizationWidget", "Form"))
        self.label.setText(_translate("VizualizationWidget", "Vizualization Widget"))
        self.pushButtonViewDownsampleMCMovie.setText(_translate("VizualizationWidget", "Downsampled MC Movie"))
        self.pushButtonInputMovie.setText(_translate("VizualizationWidget", "Input Movie"))
        self.pushButtonViewProjection.setText(_translate("VizualizationWidget", "View Projection"))
        self.pushButtonCnImage.setText(_translate("VizualizationWidget", "Correlation Image"))
        self.comboBoxProjection.setItemText(0, _translate("VizualizationWidget", "mean"))
        self.comboBoxProjection.setItemText(1, _translate("VizualizationWidget", "std"))
        self.comboBoxProjection.setItemText(2, _translate("VizualizationWidget", "max"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VizualizationWidget = QtWidgets.QWidget()
    ui = Ui_VizualizationWidget()
    ui.setupUi(VizualizationWidget)
    VizualizationWidget.show()
    sys.exit(app.exec_())
