# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viz_template_dockwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VizualizationWidget(object):
    def setupUi(self, VizualizationWidget):
        VizualizationWidget.setObjectName("VizualizationWidget")
        VizualizationWidget.resize(221, 157)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.pushButtonEvalGui = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonEvalGui.setGeometry(QtCore.QRect(10, 100, 201, 25))
        self.pushButtonEvalGui.setObjectName("pushButtonEvalGui")
        self.comboBoxProjection = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBoxProjection.setGeometry(QtCore.QRect(10, 10, 81, 25))
        self.comboBoxProjection.setObjectName("comboBoxProjection")
        self.comboBoxProjection.addItem("")
        self.comboBoxProjection.addItem("")
        self.comboBoxProjection.addItem("")
        self.pushButtonViewProjection = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonViewProjection.setGeometry(QtCore.QRect(100, 10, 111, 25))
        self.pushButtonViewProjection.setObjectName("pushButtonViewProjection")
        self.pushButtonCnImage = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonCnImage.setGeometry(QtCore.QRect(100, 40, 111, 25))
        self.pushButtonCnImage.setObjectName("pushButtonCnImage")
        self.pushButtonInputMovie = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonInputMovie.setGeometry(QtCore.QRect(10, 40, 81, 25))
        self.pushButtonInputMovie.setObjectName("pushButtonInputMovie")
        self.pushButtonCnmfMovie = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonCnmfMovie.setGeometry(QtCore.QRect(10, 70, 201, 25))
        self.pushButtonCnmfMovie.setObjectName("pushButtonCnmfMovie")
        VizualizationWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(VizualizationWidget)
        QtCore.QMetaObject.connectSlotsByName(VizualizationWidget)

    def retranslateUi(self, VizualizationWidget):
        _translate = QtCore.QCoreApplication.translate
        VizualizationWidget.setWindowTitle(_translate("VizualizationWidget", "Vizualization Widget"))
        self.pushButtonEvalGui.setText(_translate("VizualizationWidget", "Show Evaluation GUI"))
        self.comboBoxProjection.setItemText(0, _translate("VizualizationWidget", "mean"))
        self.comboBoxProjection.setItemText(1, _translate("VizualizationWidget", "std"))
        self.comboBoxProjection.setItemText(2, _translate("VizualizationWidget", "max"))
        self.pushButtonViewProjection.setText(_translate("VizualizationWidget", "View Projection"))
        self.pushButtonCnImage.setText(_translate("VizualizationWidget", "Correlation Image"))
        self.pushButtonInputMovie.setText(_translate("VizualizationWidget", "Input Movie"))
        self.pushButtonCnmfMovie.setText(_translate("VizualizationWidget", "Reconstructed post-CNMF Movie"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VizualizationWidget = QtWidgets.QDockWidget()
    ui = Ui_VizualizationWidget()
    ui.setupUi(VizualizationWidget)
    VizualizationWidget.show()
    sys.exit(app.exec_())
